title: Rafael Raya Tapia
logo: asset/img/profile.jpeg
description: ¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal

